### ISSUE TITLE
Quickstart Docker does not work. 

### ISSUE THREAD

**Issue by SteveChurch** [JamesRamm/longclaw_demo#15]
There seems to be all sorts of errors going on with some clashing versions. 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Django 1.11.17 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('django>=2.1'), {'longclaw'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/longclaw", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'django>=2.1' distribution was not found and is required by longclaw```

**Comment by JamesRamm** [comment]
Hi,
The longclaw master branch has just been updated to wagtail 2/django 2/python 3. I'll be making a 1.0.0 release of longclaw in the coming days/weeks.

This means longclaw_demo is out of date, hence your problems - I am working on it as a priority right now. 

Quickest thing I can do is pin the longclaw requirement  to the latest released version of longclaw (which is 0.2.1 in this case)
